import type { Language } from "./types";

export interface Course {
  id: string;
  emoji: string;
  title: string;
  description: string;
  language: Language;
  difficulty: "beginner" | "intermediate" | "advanced";
  topics: string[];
  vocabulary: Array<{ word: string; translation: string; example: string }>;
  scenarios: string[]; // scenario IDs from SCENARIOS
}

export const COURSES: Course[] = [
  {
    id: "business-en",
    emoji: "💼",
    title: "Business English",
    description: "Meetings, emails, presentations, negotiations",
    language: "en",
    difficulty: "intermediate",
    topics: ["Meetings", "Emails", "Presentations", "Negotiations", "Reports"],
    scenarios: ["job-interview"],
    vocabulary: [
      { word: "agenda", translation: "gündem", example: "Let's review the agenda for today's meeting." },
      { word: "deadline", translation: "son tarih", example: "We need to meet the deadline by Friday." },
      { word: "stakeholder", translation: "paydaş", example: "All stakeholders must approve the proposal." },
      { word: "leverage", translation: "kullanmak / yararlanmak", example: "We can leverage our existing technology." },
      { word: "scope", translation: "kapsam", example: "The project scope has been clearly defined." },
      { word: "milestone", translation: "kilometre taşı", example: "Reaching this milestone took six months." },
      { word: "synergy", translation: "sinerji", example: "There's great synergy between our teams." },
      { word: "outsource", translation: "dışarıya yaptırmak", example: "We decided to outsource the design work." },
      { word: "ROI", translation: "yatırım getirisi", example: "The ROI on this campaign was significant." },
      { word: "pipeline", translation: "iş akışı", example: "We have several deals in the pipeline." },
      { word: "deliverable", translation: "teslim edilecek iş", example: "The final deliverable is due next week." },
      { word: "benchmark", translation: "kıyaslama noktası", example: "Their performance sets the benchmark." },
      { word: "feasibility", translation: "uygulanabilirlik", example: "We're studying the feasibility of the plan." },
      { word: "negotiate", translation: "müzakere etmek", example: "I'd like to negotiate the contract terms." },
      { word: "consensus", translation: "fikir birliği", example: "We reached a consensus on the strategy." },
      { word: "implement", translation: "uygulamak", example: "We'll implement the new system next quarter." },
      { word: "facilitate", translation: "kolaylaştırmak", example: "She will facilitate the workshop." },
      { word: "streamline", translation: "düzene sokmak", example: "Let's streamline our hiring process." },
      { word: "delegate", translation: "yetki devretmek", example: "Good managers delegate tasks effectively." },
      { word: "leverage", translation: "kaldıraç / etki", example: "We have leverage in this negotiation." },
    ],
  },
  {
    id: "medical-en",
    emoji: "🏥",
    title: "Medical English",
    description: "Hospital, symptoms, treatment, patient care",
    language: "en",
    difficulty: "advanced",
    topics: ["Symptoms", "Diagnosis", "Treatment", "Anatomy", "Medications"],
    scenarios: ["doctor"],
    vocabulary: [
      { word: "symptom", translation: "belirti", example: "Fatigue is a common symptom of anemia." },
      { word: "diagnosis", translation: "teşhis", example: "The doctor confirmed the diagnosis after tests." },
      { word: "prescription", translation: "reçete", example: "I need to refill my prescription." },
      { word: "dosage", translation: "doz", example: "Follow the recommended dosage carefully." },
      { word: "chronic", translation: "kronik", example: "She has a chronic condition that requires monitoring." },
      { word: "acute", translation: "akut", example: "He was admitted with acute appendicitis." },
      { word: "infection", translation: "enfeksiyon", example: "Antibiotics treat bacterial infections." },
      { word: "inflammation", translation: "iltihap", example: "Ice can reduce inflammation and swelling." },
      { word: "fracture", translation: "kırık", example: "She suffered a fracture in her wrist." },
      { word: "biopsy", translation: "biyopsi", example: "A biopsy will determine if it's malignant." },
      { word: "anesthetic", translation: "anestezi", example: "Local anesthetic was used for the procedure." },
      { word: "surgery", translation: "ameliyat", example: "The surgery lasted three hours." },
      { word: "recovery", translation: "iyileşme", example: "Recovery takes about two weeks." },
      { word: "vaccine", translation: "aşı", example: "Annual flu vaccines are recommended." },
      { word: "allergic", translation: "alerjik", example: "I'm allergic to penicillin." },
      { word: "blood pressure", translation: "tansiyon", example: "Her blood pressure is slightly elevated." },
      { word: "heart rate", translation: "kalp atış hızı", example: "His resting heart rate is normal." },
      { word: "specialist", translation: "uzman doktor", example: "You should see a specialist for this." },
      { word: "referral", translation: "sevk", example: "I need a referral to a cardiologist." },
      { word: "medication", translation: "ilaç", example: "Take this medication twice daily with food." },
    ],
  },
  {
    id: "travel-en",
    emoji: "✈️",
    title: "Travel English",
    description: "Airport, hotel, restaurant, sightseeing",
    language: "en",
    difficulty: "beginner",
    topics: ["Airport", "Hotel", "Transportation", "Restaurants", "Sightseeing"],
    scenarios: ["airport", "hotel", "restaurant", "taxi"],
    vocabulary: [
      { word: "boarding pass", translation: "biniş kartı", example: "Please show your boarding pass at the gate." },
      { word: "luggage", translation: "bagaj", example: "I have two pieces of luggage to check in." },
      { word: "customs", translation: "gümrük", example: "Please declare any items at customs." },
      { word: "passport", translation: "pasaport", example: "Don't forget to bring your passport." },
      { word: "itinerary", translation: "seyahat planı", example: "Here's a copy of your itinerary." },
      { word: "reservation", translation: "rezervasyon", example: "I have a reservation under Smith." },
      { word: "vacancy", translation: "boş oda", example: "Sorry, we have no vacancy tonight." },
      { word: "check-in", translation: "giriş işlemi", example: "Check-in time is after 3 PM." },
      { word: "check-out", translation: "çıkış işlemi", example: "Check-out is by 11 AM tomorrow." },
      { word: "currency", translation: "para birimi", example: "Where can I exchange currency?" },
      { word: "guidebook", translation: "rehber kitap", example: "The guidebook recommends this restaurant." },
      { word: "souvenir", translation: "hediyelik eşya", example: "I bought a souvenir for my mother." },
      { word: "landmark", translation: "ünlü yer", example: "The Eiffel Tower is a famous landmark." },
      { word: "departure", translation: "kalkış", example: "What time is your departure?" },
      { word: "arrival", translation: "varış", example: "Our arrival time is 8 PM local time." },
      { word: "delay", translation: "gecikme", example: "There's a two-hour delay due to weather." },
      { word: "tip", translation: "bahşiş", example: "A 15% tip is customary here." },
      { word: "bill", translation: "hesap", example: "Could we have the bill, please?" },
      { word: "cuisine", translation: "mutfak (yemek kültürü)", example: "Italian cuisine is very popular here." },
      { word: "directions", translation: "yön tarifi", example: "Could you give me directions to the museum?" },
    ],
  },
  {
    id: "academic-en",
    emoji: "🎓",
    title: "Academic English",
    description: "Essays, research, lectures, debates",
    language: "en",
    difficulty: "advanced",
    topics: ["Essay writing", "Research", "Lectures", "Citations", "Debate"],
    scenarios: [],
    vocabulary: [
      { word: "hypothesis", translation: "hipotez", example: "Our hypothesis was confirmed by the data." },
      { word: "thesis", translation: "tez", example: "She's defending her thesis next month." },
      { word: "methodology", translation: "metodoloji", example: "The methodology section explains our approach." },
      { word: "analysis", translation: "analiz", example: "A thorough analysis is required." },
      { word: "synthesis", translation: "sentez", example: "The paper offers a synthesis of recent research." },
      { word: "argument", translation: "argüman", example: "Her argument was well-supported by evidence." },
      { word: "evidence", translation: "kanıt", example: "There's strong evidence to support this claim." },
      { word: "citation", translation: "alıntı", example: "Don't forget to add citations for all sources." },
      { word: "bibliography", translation: "kaynakça", example: "The bibliography includes 50 references." },
      { word: "abstract", translation: "özet", example: "The abstract summarizes the entire paper." },
      { word: "paradigm", translation: "paradigma", example: "This represents a paradigm shift in the field." },
      { word: "empirical", translation: "deneysel", example: "We need empirical evidence to back this up." },
      { word: "theoretical", translation: "kuramsal", example: "The theoretical framework is well-established." },
      { word: "peer review", translation: "akran değerlendirmesi", example: "The paper is currently in peer review." },
      { word: "plagiarism", translation: "intihal", example: "Plagiarism is taken very seriously." },
      { word: "scholarly", translation: "akademik", example: "Use scholarly sources for your research." },
      { word: "rhetoric", translation: "retorik", example: "His rhetoric was persuasive but lacked substance." },
      { word: "discourse", translation: "söylem", example: "Academic discourse follows specific conventions." },
      { word: "infer", translation: "çıkarım yapmak", example: "From the data, we can infer a strong correlation." },
      { word: "elaborate", translation: "ayrıntılandırmak", example: "Could you elaborate on that point?" },
    ],
  },
  {
    id: "tech-en",
    emoji: "💻",
    title: "Tech English",
    description: "Software, meetings, code review, agile",
    language: "en",
    difficulty: "intermediate",
    topics: ["Development", "Standups", "Code review", "Architecture", "Debugging"],
    scenarios: [],
    vocabulary: [
      { word: "deploy", translation: "yayınlamak", example: "We'll deploy the new version tomorrow." },
      { word: "framework", translation: "çerçeve", example: "Next.js is a popular React framework." },
      { word: "repository", translation: "depo (kod)", example: "Clone the repository to get started." },
      { word: "commit", translation: "kayıt (kod değişikliği)", example: "Please commit your changes daily." },
      { word: "branch", translation: "dal (kod)", example: "Create a new branch for this feature." },
      { word: "merge", translation: "birleştirmek", example: "Merge the pull request after review." },
      { word: "bug", translation: "hata", example: "I found a bug in the login flow." },
      { word: "feature", translation: "özellik", example: "This feature was requested by users." },
      { word: "scalable", translation: "ölçeklenebilir", example: "We need a scalable solution." },
      { word: "endpoint", translation: "uç nokta (API)", example: "The endpoint returns user data." },
      { word: "latency", translation: "gecikme süresi", example: "Latency on this server is too high." },
      { word: "throughput", translation: "veri akış hızı", example: "We improved throughput by 40%." },
      { word: "refactor", translation: "yeniden düzenlemek", example: "Let's refactor this function." },
      { word: "deprecated", translation: "kullanımdan kaldırılmış", example: "That method is deprecated." },
      { word: "rollback", translation: "geri alma", example: "We had to rollback the deployment." },
      { word: "migration", translation: "geçiş", example: "The database migration ran successfully." },
      { word: "dependency", translation: "bağımlılık", example: "Update all dependencies regularly." },
      { word: "production", translation: "canlı ortam", example: "Don't push directly to production." },
      { word: "staging", translation: "test ortamı", example: "Test it in staging first." },
      { word: "agile", translation: "çevik", example: "We follow agile methodology." },
    ],
  },
];

export function getCourse(id: string): Course | undefined {
  return COURSES.find((c) => c.id === id);
}
